baseURL = ''https://tomd6.github.io/'
languageCode = 'fr-fr'
title = 'mon site'
theme = 'iutdelens'

[params]
    author = "Moi (C'est moi)"
    authorImage = "/img/moi_auteur.jpg"
    ImageMoi = "/img/moi.jpg"

[[menu.main]] 
  name = "À propos" 
  url = "/a-propos-de" 
 
[[menu.main]] 
  name = "Blog" 
  url = "/blog"

[[menu.main]]
  name = "Projet"
  url = "/projet"

[[menu.footer]] 
  name = "À propos" 
  url = "/a-propos-de"

[[menu.social]] 
  name = "GitHub" 
  url = "https://github.com/VotreCompteGithub" 
  pre = "<i class='fab fa-github'></i>" 
 
 
[[menu.social]] 
  name = "Twitter" 
  url = "https://twitter.com/cest_dimanche" 
  pre = "<i class='fab fa-twitter'></i>"
